# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Deploy Android (zh-CN)

on: workflow_dispatch

permissions:
  contents: write

env:
  GIT_USER_EMAIL: '41898282+github-actions[bot]@users.noreply.github.com'
  GIT_USER_NAME: 'github-actions[bot]'

jobs:
  build_for_Android_zh_CN:
    name: Android
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4

        - name: Install flutter
          uses: subosito/flutter-action@v2
          with:
            channel: 'stable'
            cache: true

        - uses: actions/setup-java@v3
          with:
            distribution: 'zulu'
            java-version: '17'
            cache: 'gradle'
      
        - name: Cache pubspec dependencies
          uses: actions/cache@v3
          with:
            path: |
              ${{ env.FLUTTER_HOME }}/.pub-cache
              **/.packages
              **/.flutter-plugins
              **/.flutter-plugin-dependencies
              **/.dart_tool/package_config.json
            key: build-pubspec-${{ hashFiles('**/pubspec.lock') }}
            restore-keys: |
              build-pubspec-

        - name: Flutter pub get
          run: flutter pub get

        - name: Initialize git config
          run: |
            git config --local user.name $GIT_USER_NAME
            git config --local user.email $GIT_USER_EMAIL

        - name: Bump up version
          run: |
            flutter pub run cider bump build --bump-build
            echo "BUMP_VERSION=$(flutter pub run cider version)" >> $GITHUB_ENV

        - name: Create apk file
          run: |
            echo -n "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode --output ./android/release.keystore
            export ANDROID_KEYSTORE_PASSWORD="${{ secrets.ANDROID_KEYSTORE_PASSWORD }}"
            export ANDROID_KEY_ALIAS="${{ secrets.ANDROID_KEY_ALIAS }}"
            export ANDROID_KEY_PASSWORD="${{ secrets.ANDROID_KEY_PASSWORD }}"            
            flutter build apk --no-tree-shake-icons --release
            mv ./build/app/outputs/flutter-apk/app-release.apk ./build/app/outputs/flutter-apk/miria-$BUMP_VERSION.apk

        - name: Create tag and release note
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            gh release create v$BUMP_VERSION --generate-notes --draft ./build/app/outputs/flutter-apk/miria-$BUMP_VERSION-zh-CN.apk
